### ISSUE TITLE
char icons and emote buttons use nearest neighbor - should use bilinear/bicubic

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/webAO#106]
It looks really crusty on emote buttons/char icons with irregular size
![image](https://user-images.githubusercontent.com/3470436/158061518-e64a5345-6e50-4744-9163-01a52b567226.png)

**Comment by stonedDiscord** [comment]
don't use charicons with irregular size

**Comment by oldmud0** [comment]
also note to this, we can't set downscaling to smooth and upscaling to nearest neighbor like desktop can
