### ISSUE TITLE
Message parsing feels sluggish

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/webAO#107]
Message parsing feels sluggish. After you send a message, text box appears, hangs for a bit, and only after that small delay it starts showing you the text.
Instead, it should immediately start processing with the first character being displayed, meaning that instead of starting parsing at 0th character and waiting the delay, it should start at 1th character already displayed.

https://user-images.githubusercontent.com/3470436/158061622-98d6f8ba-80cf-4cfd-8502-ecab08f26884.mp4

**Comment by Crystalwarrior** [comment]
Also it seems like that 0th character is blipped for some reason before any char even shows up?

**Comment by stonedDiscord** [comment]
in AA the box is empty before the first character appears

**Comment by Crystalwarrior** [comment]
> in AA the box is empty before the first character appears

It doesn't take *this long* in AA

**Comment by stonedDiscord** [comment]
everything else was slow too
was hopefully fixed with b60b656fceee55f689de2bdb30a86b7fd42e6810
