### ISSUE TITLE
setEmote makes my browser lag very bad

### ISSUE THREAD

**Issue by stonedDiscord** [AttorneyOnline/webAO#122]
the 4 requests to check for a sprite seem to task my firefox so bad that it doesn't accept mouseclick or keyboard input. this means that i can't even type in a message in an active room

**Comment by caleb-mabry** [comment]
This is likely due to `fileExistsSync` in the `setEmote` method. We do have an asynchronous counterpart `fileExists` that can be used instead. This should resolve the issue.

**Comment by stonedDiscord** [comment]
i had a recursive loop of death in the bg code
fixed it with b60b656fceee55f689de2bdb30a86b7fd42e6810
