### ISSUE TITLE
IC chat unnecessary scrolling

### ISSUE THREAD

**Issue by vintprox** [AttorneyOnline/webAO#13]
**Actual behavior:** AAAAAARGH! I can't just list old messages because of new ones popping up.

**Expected behavior:** in-character chat is automatically scrolled only when user lists recent lines, thus allowing to scroll through old ones without being distracted.

**Current workaround:** switch to silent room and list through older messages without distraction.

**Comment by oldmud0** [comment]
On my end, I get the opposite behavior - it's difficult to get it to auto-scroll, and when the log is not focused, the log fails to auto-scroll.

**Comment by stonedDiscord** [comment]
same
