### ISSUE TITLE
Music selection is distractive on mobile

### ISSUE THREAD

**Issue by vintprox** [AttorneyOnline/webAO#14]
**Actual behavior:** it requires 4 presses (press combobox, select option, press combobox again, then press "Back" or same option to return) to change the music/area and continue playing on mobile Chrome! I think it's because of "double-click it to change" feature.

**Expected behavior:** press button (which should be visible and related to music), select track - and voila!

**Mobile view:**
![mobile view of webAO](https://i.imgur.com/2Flqnk1.png)

**Comment by vintprox** [comment]
And maybe, just maybe make it narrower on mobile, since the actual list appears in options modals?

![](https://i.imgur.com/yF9j3b3.png)

**Comment by oldmud0** [comment]
I don't have a mobile-specific preset for GoldenLayout. You should make an overarching issue for adding a layout preset specifically for mobile.

**Comment by vintprox** [comment]
Got it. And speaking of mobile users: they may not notice the combobox, and Music title just makes less sense for them, because it's like really confusing.
The solution is to make icon buttons dedicated for area selection and music selection separated. Icons at least can lead user to try them out.

**Comment by stonedDiscord** [comment]
6c12610616ec0f8fa0c2907622fa26095c70b4e6

mobile browsers are using a dropdown box which is the correct way of handling the SELECT tag
i changed it to be a multiple choice element and undo the option so you can't select multiple tracks.
should be fixed with this

**Comment by vintprox** [comment]
@stonedDiscord seems more buggy on mobile now: it takes more taps to uncheck what I don't need (well, selects on mobile are something).

![](https://i.imgur.com/r6FSKPJ.png)
![](https://i.imgur.com/zfYhNwq.png)

It should not be multiselect, because it simply complicates the things.

Revert and make maybe some background image for select or `<label>` with icon which brings the focus on select. Ensure that user can simply click once to switch the track, **not twice**.

Also, as I mentioned before, it would be good to finally separate the rooms list from music. I have at least one very strong reason for that: I don't want to mess between room and track selection, it's just bad UX.

**Comment by stonedDiscord** [comment]
so it got worse on android
the select tag is weird on there

the server owners add the rooms to the music list, so users don't have to switch between the lists on the desktop client. a vanilla server has 4 rooms and none on the musiclist

**Comment by stonedDiscord** [comment]
![grafik](https://user-images.githubusercontent.com/10584181/61389282-f175f880-a8b8-11e9-85e3-fbe2d9595504.png)
this is how it looks on a desktop browser and it only takes one click
i was hoping to achieve the same thing on mobile by changing it to a multiselect

**Comment by vintprox** [comment]
@stonedDiscord yes, it's understandable, however it seems that drawing this long list instantly won't turn out good, so this task suits internal list modal better.

I wonder how to show Music button **only** on mobile devices then (if it'd be visible enough, then you can hide select with `visibility: hidden; width: 0; height: 0;`)...

**Comment by vintprox** [comment]
Huh, I think quick fix is revert multiselect and give the combobox a background image with **music icon**. It will bring user's attention to music control. On desktop they probably will see this icon on background too, but it's nothing now, really.

**Comment by oldmud0** [comment]
On mobile, replace the entire music panel with a music combo box on the main panel.

**Comment by vintprox** [comment]
I like this idea: the need of "Music" panel then vanishes! Maybe even music button would not be needed (but leave some "Music" label).

**Comment by stonedDiscord** [comment]
i swithced to onchange and it works much better
now i only need to come up with an UX solution

**Comment by stonedDiscord** [comment]
it's 2 taps now on chrome android
