### ISSUE TITLE
The enter button doesn't work right sometimes on mobile(WEB on mobile)

### ISSUE THREAD

**Issue by PotatoDC** [AttorneyOnline/webAO#141]
Yea I'll send a vid of the problem, it happened in multiple servers and it happened with some other peeps too, also happens on the attorneyoffline thing, it gets annoying only being able to talk in the ooc, tell me if the vid doesn't work cuz I have no idea

https://user-images.githubusercontent.com/102555677/167205260-845b09af-ef30-4f28-a9b1-2405337b7c13.mp4

**Comment by AwesomeAim** [comment]
Use webtest.

**Comment by stonedDiscord** [comment]
this was fixed in a866a3267e129218b062a1185cbf297b518239c8
