### ISSUE TITLE
WebAO does not send CC when spectator is selected

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/webAO#147]
This causes a twofold issue :
1. The server is unable to free the character as it does not know about the change.
  1.1 The "spectator" WebAO client is still able to send messages with the last selected emote. 
2. Servers that rely on the CC packet to determine the spectator state are unable to enforce spectator limitations.

**Comment by caleb-mabry** [comment]
@Salanto Is this issue still happening? I'm not sure I'm able to recreate the issue you are experiencing

**Comment by stonedDiscord** [comment]
fixed in 3e8704e509f65bb5896e2efa4d49e8aaa5431799
