### ISSUE TITLE
Loading is disturbing

### ISSUE THREAD

**Issue by vintprox** [AttorneyOnline/webAO#15]
On page enter using mobile browser we get this:

![](https://i.imgur.com/ZmOZUsH.png)
![](https://i.imgur.com/mCjtTGH.png) 

Such indication doesn't look promising: first of all, this overflowing, second, estimated percentage - for music it takes to wait until 920 is reached which is kind of weird.

Now about **loading speed**. Does it ignore cache? Let alone characters loading - it's fast enough. But I expect to being able to play without loading music - load it in background (this is such minor information for player).

**Comment by oldmud0** [comment]
That is a single tree in a forest of issues with webAO.

**Comment by vintprox** [comment]
@oldmud0 one of my hobbies is investigating such forests :)

**Comment by stonedDiscord** [comment]
fixed
9403549f72a601454970d36fa30e7e2f012352e2
will update the website soon :tm:

**Comment by vintprox** [comment]
Wow! It also made turbo speed loading! 👍💪![](https://i.imgur.com/xuoHIup.png)

**Comment by oldmud0** [comment]
So when are we going to use Vue for the UI :v

**Comment by vintprox** [comment]
@oldmud0 till the cows come home 😂 It requires major refactoring, plus Vue 3.0 is not yet released (it looks promising).
