### ISSUE TITLE
Main panel interferes with Log

### ISSUE THREAD

**Issue by vintprox** [AttorneyOnline/webAO#16]
There is Main panel provided as sibling to Log (IC chat). Everytime I want to change role, name and other settings I have to switch between "Log" and "Main" tabs, thus missing fast flow of messages listed in log.
What if there was an option to displace it near by Server Chat (OOC chat)? That would be just perfect!

**Comment by oldmud0** [comment]
GoldenLayout can do that. I just have to re-enable the ability to close panes.

**Comment by stonedDiscord** [comment]
![pane](https://user-images.githubusercontent.com/10584181/77231477-78dbe000-6b9b-11ea-93ec-921da9c87296.gif)
