### ISSUE TITLE
IC input has no padding

### ISSUE THREAD

**Issue by vintprox** [AttorneyOnline/webAO#17]
In-character input field is pretty narrow in height and there's no empty space on left and right edges which is not mobile-friendly. It could be somewhat 20 px bigger both sides: please, add some padding.

**Comment by stonedDiscord** [comment]
there is a little "maximise" button at the top right of the IC window which makes it fill the entire screen. Does that work out for you?

**Comment by vintprox** [comment]
@stonedDiscord that is no use. We need bigger tap size for mobile, btw it would also be good for PC users as well.
By padding I mean the edges around typed text to make it easy to press/focus and edit.

**Comment by vintprox** [comment]
Look, I can easily miss this field... My fingers are not weirdly thin for that.

![](https://i.imgur.com/i9Cpnbp.png)

**Comment by stonedDiscord** [comment]
![grafik](https://user-images.githubusercontent.com/10584181/61325515-37798080-a815-11e9-9df0-3077a70df06c.png)
is this better?
i added 4px of padding, 20 seems a bit much

**Comment by vintprox** [comment]
@stonedDiscord I mean add 10px at each side, 4px is still small

**Comment by stonedDiscord** [comment]
![grafik](https://user-images.githubusercontent.com/10584181/61328374-2cc1ea00-a81b-11e9-9f98-efd5c0bab4b2.png)

f54f9ce8f8860c1afed433c5043d304d9cb30390

i increased the font size which doubled the box size

**Comment by vintprox** [comment]
@stonedDiscord thanks, that's not bad! Tho it's still not very friendly for mobile, because user may want to select some text to remove/replace/copy, and without padding at left and right edges it's a pain for fingers.

I'd gladly make some changes if I had laptop. Unfortunately on phone it gets a ton of loading before ever beginning to edit any code.

Add this line to stylesheet:

```
padding: 0 10px;
```

**Comment by vintprox** [comment]
Thanks for understanding 😊
