### ISSUE TITLE
Web text display error

### ISSUE THREAD

**Issue by Wilsein** [AttorneyOnline/webAO#178]
Web bugs out when displaying the characters "<" and ">" in the area name box.

![Screenshot 2023-01-07 10 31 46 PM](https://user-images.githubusercontent.com/122189096/211177999-59aea817-1b89-46d5-86ff-a127e2d429f1.png)

The name of this area of the SoC server is "The Mighty Forest <Temple>". Web misreads it as "The Mighty Forest &It;Temple&gt;" as can be seen in the screenshot.

I am also unable to join that area in web, which is most likely a side effect of this error.

This error also occurs on the showname box, so they're most likely correlated.

![Screenshot 2023-01-07 10 42 41 PM](https://user-images.githubusercontent.com/122189096/211178176-859b5990-5ac0-4d32-b048-6ea1358d3487.png)

**Comment by stonedDiscord** [comment]
yeah that is intentional so people don't send you random HTML tags and take over your browser

**Comment by stonedDiscord** [comment]
fixed it
