### ISSUE TITLE
png character sprites are not supported

### ISSUE THREAD

**Issue by stonedDiscord** [AttorneyOnline/webAO#19]
add a fallback to .png for missing .gif sprites

**Comment by vintprox** [comment]
Maybe through handling 404 status by `*.gif` URL replace it with `*.png`.

**Comment by oldmud0** [comment]
That will slow down overall asset loading. Both PNG and GIF URLs should be requested simultaneously, and the one that works should be selected.

**Comment by vintprox** [comment]
Good

**Comment by stonedDiscord** [comment]
characters ending in _HD will load PNG sprites.
This is a hack to get DRO sprites to work.

**Comment by stonedDiscord** [comment]
fixed with #48
