### ISSUE TITLE
Area lists are cut off partially

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/webAO#190]
![image](https://github.com/AttorneyOnline/webAO/assets/30537683/05247b99-4f28-45bf-81b1-ed8dfe066426)
![image](https://github.com/AttorneyOnline/webAO/assets/30537683/7ef23b3c-d6e9-4c85-bf2a-9589a4a35c16)

![image](https://github.com/AttorneyOnline/webAO/assets/30537683/0dc2f426-3484-402f-8ccf-e751c85e6162)

![image](https://github.com/AttorneyOnline/webAO/assets/30537683/488813f6-0535-474e-b3a4-ee71fe93a277)

![image](https://github.com/AttorneyOnline/webAO/assets/30537683/1b5f64cb-7584-46bf-a8dd-2f154be4d647)

I'm not sure if it's a server issue or a web issue or if it's even something new but recently web users have been reporting that there is no third area in my server, which is weird, so I added a fourth and now the third one is visible but the fourth is not. The area is still accessible via the /area # command.

For akashi servers, the area is cut off completely, while for other servers, only the player count and status (IDLE) is cut off.

**Comment by Salanto** [comment]
Secret areas for your AO2.

**Comment by stonedDiscord** [comment]
What does your music list look like

**Comment by AwesomeAim** [comment]
Mine? It's just a json file.

**Comment by AwesomeAim** [comment]
I don't use web. If it's fixed, then that's fine and you can close it.
