### ISSUE TITLE
Attorneyoffline.de CORS issue

### ISSUE THREAD

**Issue by OmniTroid** [AttorneyOnline/webAO#216]
The default policy of most modern web browsers is to not accept cross origin requests unless the CORS header is present. The host attorneyoffline.de, which is the default content repository does not supply these headers when the resource is not found, which doubles the amount of errors in console:

![image](https://github.com/AttorneyOnline/webAO/assets/14360110/c96e2cbc-e8f0-41ee-b618-6a25ab035b36)

making sure attorneyoffline.de (and indeed, all content repositories) always provides these headers makes sure that these errors do not fill up the console.

**Comment by stonedDiscord** [comment]
CORS on a 404 doesn't make sense
and I couldn't change it even if I wanted with the cheap webhost I have

Also not a webAO issue
close your browser if the errors bother you
