### ISSUE TITLE
Playerlist related issues

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/webAO#228]
The following issues have been found :

- Users can't scroll the player list
- The player list shows all players of the server, not the ones in the current area
- The mod buttons are visible to people who are not authenticated.

**Comment by stonedDiscord** [comment]
- [X] Users can't scroll the player list
- [ ] The player list shows all players of the server, not the ones in the current area
- [X] The mod buttons are visible to people who are not authenticated.
