### ISSUE TITLE
Occupied characters: implicit indication

### ISSUE THREAD

**Issue by vintprox** [AttorneyOnline/webAO#23]
It should be obvious which characters are already occupied, if user doesn't have a trouble with recognizing slightly dark from light.

I think occupied characters should be marked more explicitly: maybe add some marker?

Also current solution applies darkness filter to the image, which is not quite compliant, because some characters' icons can have transparency. Would not it be easy to fix it once in webAO rather than contacting content creators? Because I see such thing is happening on official server:

![](https://i.imgur.com/XDOJjGa.png)

(emphasis on Klavier Gavin in the middle) It just seems off among other icons.

Solution is simple: add gray background to icons, add `:before` which will be black square overlay with slight transparency on top of whole icon. (I hope these image icons have some wrapper to accomplish this.)

**Comment by stonedDiscord** [comment]
these icons are called "demothings" and come with the character files themselves

**Comment by oldmud0** [comment]
They used to not come with the character in the old AO1 days. Yikes.

**Comment by stonedDiscord** [comment]
ok so i looked it up and webAO does apply a "dark" class to taken characters. i think it's not working with klavier because he has a transparent background which is a content issue

**Comment by stonedDiscord** [comment]
![grafik](https://user-images.githubusercontent.com/10584181/61873897-4fbd5f80-aee7-11e9-83f0-dac3ec05b3e0.png)

**Comment by vintprox** [comment]
As I recall, if opaque background is expected for all icons, there should be one in stylesheet.

**Comment by stonedDiscord** [comment]
97d81ab021b9021838e84c9adc833ee3c13854a2 fixed this by making the entire image opaque on the now dark background
