### ISSUE TITLE
Area list not cleared after reconnect

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/webAO#43]
**Expected behavior:** On pressing the reconnect button after being unexpectedly disconnected, the area list should show the correct list of areas.

**Actual behavior**: The area list shows a repeated list of areas:
![area list](https://user-images.githubusercontent.com/5247009/71632292-602ee000-2bd3-11ea-944b-4f226ae92144.png)

**Solution**: Clear the area list upon pushing the reconnect button.

**Comment by stonedDiscord** [comment]
https://www.youtube.com/watch?v=vjW8wmF5VWc
