### ISSUE TITLE
"You must insert a name with at least one letter" with default OOC name

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/webAO#5]
**Expected behavior**: An OOC message is sent with the default webAO name.
**Actual behavior**: An OOC message is unable to be sent because the server does not seem to recognize our name (is it sending an empty string instead?). Instead, we must change it first in the Settings menu.

**Comment by JamesBCrazy** [comment]
This also occasionally occurs when switching characters. (Cannot consistently reproduce.)

**Comment by vintprox** [comment]
Still.
I think name should be shared between sessions (proposal). Or... well, at least make some prompt for asking a name on page enter.

**Comment by oldmud0** [comment]
This error is sent by tsuserver when the specified OOC name is already taken. It's kind of unintuitive.

**Comment by vintprox** [comment]
@oldmud0 Should I file a request for auto-setting random name (web[100-999]) on join? That would be temporary solution.

**Comment by oldmud0** [comment]
It's not that simple because the OOC name is set every time the client sends a message. So if the web client keeps trying to use web1, then tsuserver will set a random name for every message sent.

**Comment by vintprox** [comment]
@oldmud0 oh, then either way, it's the task of retrieving new name from server, or setting it in *client*.
Can we adopt second solution for the players' sake? 😉

**Comment by vintprox** [comment]
@oldmud0 What about this...?

```
document.getElementById("OOC_name").value = 100 + Math.floor(Math.random() * 900)
```

**Comment by vintprox** [comment]
Let's review `loadResources` function in `client.js`. How frequently it is called? Once per page load or it's reusable? `this.playerID` turns out to be equal `1` in many cases, so it can be easily replaced with `(100 + Math.floor(900 * Math.random()))` to temporarily solve the issue?

**Comment by oldmud0** [comment]
You can certainly set an initial random OOC name and then persist it in web storage.

**Comment by vintprox** [comment]
@oldmud0 Well, the question is how many times `loadResources` is called? If once per page load, then of course, no prob, I even can make this change, otherwise I dunno.

**Comment by oldmud0** [comment]
Only once.

**Comment by stonedDiscord** [comment]
we could initialize the name to be web + the last 3 numbers of the fingerprint
it is random enough for this and helps with moderating really stupid spammers
(((which we have a lot of)))

**Comment by vintprox** [comment]
I think first-time prompt asking for nickname would be more compliant fingerprint, then keep it in cookies, and any changes as well.

**Comment by stonedDiscord** [comment]
we don't store cookies because of EU regulations
or do you want a banner "pwease click accept to continue with our cookies"

**Comment by stonedDiscord** [comment]
the user agent isn't transmitted over websockets and not unique enough + people change IPs all the time.
My ISP changes it every night, so do most.

**Comment by vintprox** [comment]
@stonedDiscord if it makes good UX, by all means, yes.

**Comment by stonedDiscord** [comment]
no it means bad UX because of this:
![grafik](https://user-images.githubusercontent.com/10584181/61470254-08801d80-a981-11e9-8bf8-757ad19266ff.png)

**Comment by vintprox** [comment]
@stonedDiscord you are not forced to show it in annoying way. Make it appear bottom and quite little. And not modal.

**Comment by stonedDiscord** [comment]
i think i will use webstorage instead for the volume settings and the ooc name

**Comment by vintprox** [comment]
@stonedDiscord as soon as saved data is not used for tracking same user between sessions, no warning is required!

(Regulation doesn't relate to just cookies btw.)

**Comment by oldmud0** [comment]
"by selecting a character you agree for your name to be stored in local storage"

**Comment by vintprox** [comment]
I don't even think these regulations fall in the scope of sketchy nicknames that players give themselves in the net. So no worries about legal stuff?

**Comment by oldmud0** [comment]
sD always has concerns about GDPR - don't ask me why.

**Comment by stonedDiscord** [comment]
because there are law offices who earn money by doing nothing but looking for websites that use tracking cookies but don't have a banner

i don't want to get involved with real attorneys

**Comment by stonedDiscord** [comment]
9b16ff9c582a5a3e1bb7a766eabfbc718bad2808 fixed this
i will add a notice to the settings page saying that changing anything will save it
