### ISSUE TITLE
Support for areas in a separate packet.

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/webAO#64]
AO 2.8 support sending the areas and music list as separate packets. But webAO doesn't yet. This causes webAO to not load the area list on servers supporting this feature.

Steps to reproduce:
1. http://web.aceattorneyonline.com/client.html?mode=join&ip=107.161.23.183:50009
2. Try to find the area list

**Comment by stonedDiscord** [comment]
if i see this correctly, it parses the OOC message that gets sent by tsuserver
this is really cringe

**Comment by stonedDiscord** [comment]
https://github.com/Crystalwarrior/KFO-Server/commit/271e003039249d4f2c0a1d62d4e0f8552b856caa#diff-0e98da5512a62288434cac909098dcbc

this broke the FL# format, thus webAO using old loading

not a webAO bug

**Comment by oldmud0** [comment]
Fixed in https://github.com/Crystalwarrior/KFO-Server/commit/0cef12b177ecce197b47f009cfa54b1df7ec61d2.
