### ISSUE TITLE
Support for 2.8ish change of position

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/webAO#65]
On 2.6 the GUI for changing the pos would just run the /pos command. But on 2.8 this is different.
webAO doesn't support the 2.8 way and this render web users unable to change position.
I'll investigate on the details of how this works on 2.8

Steps to reproduce:

1. http://web.aceattorneyonline.com/client.html?mode=join&ip=107.161.23.183:50009
2. Try to change position by either the menu or command.

**Comment by stonedDiscord** [comment]
if i see this correctly, it parses the OOC message that gets sent by tsuserver
this is really cringe

**Comment by stonedDiscord** [comment]
done
