### ISSUE TITLE
Music list AM#% and SM#% packets are handled differently from 2.9

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/webAO#83]
Feature parity issue, causes certain areas to be processed as songs instead of areas due to this.
Bug detected on Killing Fever Online after introducing a Dummy area for some functionality
https://github.com/Crystalwarrior/KFO-Server/blob/2c0b025705af7c1469c11c55ea63eb2afc7a4746/server/network/aoprotocol.py#L299-L321

Client parsing logic of SM packet
https://github.com/AttorneyOnline/AO2-Client/blob/74d01e81fbcb9e423cd18ee90eacddbb47f01b14/src/packet_distribution.cpp#L374-L415

**Comment by Crystalwarrior** [comment]
Figured out where the difference happens.
https://github.com/AttorneyOnline/webAO/blob/f9b62a97a0795c41b6fd3193bc10df7f18ff908f/webAO/client.js#L1021

Workaround on KFO is to not use ===, which is annoying.

**Comment by stonedDiscord** [comment]
other servers use === for music categories
