### ISSUE TITLE
Change Music packet ignores the Channel variable, plays music in incorrect channel

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/webAO#86]
Music is always being played in the main channel, despite there being a concept of multiple different music channels introduced in 2.8. This results in WebAO having interrupted music, especially on servers which have ambience system in place, like KFO-Server.
What happens on KFO is that any time you move from area to area, each area has its own associated ambience, and silence also counts as ambience it sends the client. In client, it plays on the proper channel. On webAO, it ignores the channel argument of the packet, and plays silence in the main channel.

There's 2 solutions:
1) Implement the channel system for WebAO, making it possible to play multiple music tracks at once.
2) If channel argument exists and is more than 0, the main channel, simply ignore the packet. Otherwise, play the track.

The 2nd solution is the lazy way that doesn't implement functionality for ambience, and I deem it the lame way, but it's better than having music be just bugged.

The code for channels in Client is here:
https://github.com/AttorneyOnline/AO2-Client/blob/74d01e81fbcb9e423cd18ee90eacddbb47f01b14/src/aomusicplayer.cpp#L111-L112

Maximum channels number is 4, so channel 0 is the usual main channel, and 1-3 are free channels that can be used by servers for any purpose:
https://github.com/AttorneyOnline/AO2-Client/blob/master/include/aomusicplayer.h#L21

**Comment by Crystalwarrior** [comment]
https://github.com/Crystalwarrior/KFO-Server/issues/10

**Comment by stonedDiscord** [comment]
channels work tho

https://github.com/AttorneyOnline/webAO/blob/master/webAO/client.js#L760-L762

**Comment by stonedDiscord** [comment]
fixed
https://github.com/AttorneyOnline/webAO/commit/4fcd41014846ff3c9976362ab8d5473e519fef91
