### ISSUE TITLE
.webp (and .apng?) preanimations do not function.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/webAO#89]
I tested this in multiple servers to be sure. .webp animations (a and b) themselves work fine, but not if they're to be used as preanimations, and I have had several others on web confirm that they could not see the preanimation if it was .webp. I found the same issue with .apngs, but it also worked on vanilla, which vanilla has .apngs for client at least, so I'm not totally sure (maybe it still uses .gifs or has something extra that other servers like mine and HDF don't).

In summation, .webp preanimations don't show on web, whereas they show fine on client.

**Comment by stonedDiscord** [comment]
yes, web currently can't determine the animation length of apng or webp files

for gifs, this very cursed function is used which adds up the frametimes
https://github.com/AttorneyOnline/webAO/blob/master/webAO/client.js#L1924
i don't know how to parse raw webp in js

**Comment by oldmud0** [comment]
you should be able to install a cursed webp and apng library from npm

**Comment by stonedDiscord** [comment]
we solved it without 3MB of javascript and i pretty much wrote my own
this works as of 52b79f4b5ffce7679fa5fcceeb80d615ad0cdf16
