### ISSUE TITLE
GAA chatbox using wrong fonts

### ISSUE THREAD

**Issue by JauCR** [AttorneyOnline/webAO#90]
Hey, I noticed the The Great Ace Attorney chatbox theme is using the wrong fonts, I can send the actual ones if you want so it's more accurate to the ingame look.

**Comment by stonedDiscord** [comment]
this was done back when TGAA had no official translation and i used the fan translations font.

what was the name of the new TGAA font again?

**Comment by JauCR** [comment]
It's FOTToplar for the textbox and FOT-Skip Std B for the nameplates. FOTToplar doesn't support Russian, but I merged it with the Russian ingame font, I can send it to you on Discord or email

**Comment by stonedDiscord** [comment]
those are comercial fonts by a japanese company called Fontworks
i can include them in the CSS so they are displayed if you have them installed but i can not upload them due to copyright concerns.

**Comment by semeniukjen** [comment]
> It's FOTToplar for the textbox and FOT-Skip Std B for the nameplates. FOTToplar doesn't support Russian, but I merged it with the Russian ingame font, I can send it to you on Discord or email

Can we contact about this version of font please?
