### ISSUE TITLE
Static .webp sprites don't work

### ISSUE THREAD

**Issue by Satoru-1816** [AttorneyOnline/webAO#99]
.webps that act like PNGs don't show up at all, unless they have (a)/(b) prefixes. They're a better alternative to PNGs thanks to being able to cut down sprites' size, so it would be nice to have them display like in client

**Comment by caleb-mabry** [comment]
@Satoru-1816 , if you have a server and an example character, I would love to fix this for you. I believe a recent PR may have fixed this issue but please let me know!

**Comment by Satoru-1816** [comment]
Thanks! It isn't fixed yet but check Super Spiral Gaming, there's a Rantaro Amami_EX with static .webps. Pretty sure it can serve for testing

**Comment by caleb-mabry** [comment]
@Satoru-1816 Can you confirm this issue has been resolved in http://webtest.aceattorneyonline.com/ ?
If it has, please close the issue!

**Comment by Satoru-1816** [comment]
@caleb-mabry Same as before. Same thing happens with other chars

![image](https://user-images.githubusercontent.com/81326989/157974964-bdbb15b8-7bac-4ba1-89ba-04a1623aaccf.png)
![image](https://user-images.githubusercontent.com/81326989/157975029-125bd77b-70fb-47db-a468-88713cb22943.png)
